# Generated by Django 4.2.5 on 2023-09-24 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("filmes_app", "0003_inserir_genero_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="genero",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="filmes_app.genero",
            ),
            preserve_default=False,
        ),
    ]
